name: Feedback Form
description: Submit your feedback for Several Dozen Goblins
title: "[Feedback] Issue with Controller or General Feedback"
labels: "user feedback"
assignees: ["loteque", "jonathandavidlewis"]
projects: "loteque/6"

body:
  - type: markdown
    attributes:
      value: |
        **Did you experience any issues with your controller?**
  - type: textarea
    id: controller_issues
    attributes:
      label: Describe any issues with your controller
      description: Please provide as much detail as possible about any problems you encountered with your controller.
      placeholder: Describe the issue here
      validation:
        required: true
  - type: markdown
    attributes:
      value: |
        **We would love to hear anything you would like to share about your experience with Several Dozen Goblins.**
  - type: textarea
    id: general_feedback
    attributes:
      label: General Feedback
      description: Share your overall experience and any additional comments.
      placeholder: Share your thoughts here
  - type: input
    id: email
    attributes:
      label: Email
      description: Enter your email address if you are okay with us contacting you for clarification on your feedback.
      placeholder: Your email address
      validation:
        required: false
  - type: checkbox
    id: contact_permission
    attributes:
      label: Is it okay if we contact you for clarification on your feedback?
      options:
        - label: Yes, you can contact me
          required: false
  - type: conditional
    attributes:
      if:
        any:
          - general_feedback != ""
          - contact_permission == true
      then:
        - type: markdown
          attributes:
            value: |
              **Technical Information**
        - type: textarea
          id: input_device
          attributes:
            label: What input device are you using?
            description: We detected you are using (input device)
            placeholder: Describe your input device
        - type: textarea
          id: system_info
          attributes:
            label: System Information
            description: Please include your operating system, input device, browser, and hardware.
            placeholder: Describe your system information here
        - type: checkbox
          id: info_permission
          attributes:
            label: Is it okay to include this information?
            options:
              - label: Yes, you can include this information
                required: false
  - type: markdown
    attributes:
      value: |
        **Opt-in**
